CREATE DATABASE BDMedicamentos
GO
USE BDMedicamentos
SET DATEFORMAT 'YMD'
GO

CREATE TABLE Laboratorios(
IDLaboratorio INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR (50) NOT NULL,
Cuit CHAR(11) NOT NULL UNIQUE
);
GO

CREATE TABLE Direccion(
IDDireccion INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDLaboratorio INT NOT NULL FOREIGN KEY REFERENCES Laboratorios(IDLaboratorio),
Calle VARCHAR(50) NOT NULL,
Altura VARCHAR(5) NULL,
Localidad VARCHAR(50) NOT NULL,
CP VARCHAR(5) NOT NULL, 
Observaciones VARCHAR(255) NULL
);
GO

CREATE TABLE Medicamentos (
IDMedicamento INT NOT NULL PRIMARY KEY IDENTITY(1,1),
NombreComercial VARCHAR(50) NOT NULL,
PrincipioActivo VARCHAR(50) NOT NULL,
Tipo CHAR(1) NOT NULL CHECK(Tipo IN ('C', 'P')),
IDLaboratorio INT NOT NULL FOREIGN KEY REFERENCES Laboratorios(IDLaboratorio),
PrecioUnitario DECIMAL(12,2) NOT NULL
);
GO

CREATE TABLE Ingresos(
IDIngreso INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDLaboratorio INT NOT NULL FOREIGN KEY REFERENCES Laboratorios(IDLaboratorio),
CantidadLotes INT NOT NULL DEFAULT (0),
Importe DECIMAL(12,2) NOT NULL DEFAULT (0),
Fecha DATETIME NOT NULL CHECK(Fecha <= getdate())
);
GO

CREATE TABLE Lotes(
IDLote INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDMedicamento INT NOT NULL FOREIGN KEY REFERENCES Medicamentos(IDMedicamento),
IDIngreso INT NOT NULL FOREIGN KEY REFERENCES Ingresos(IDingreso),
FechaVencimiento DATE NOT NULL CHECK(FechaVencimiento >= getdate()),
Stock INT NOT NULL DEFAULT (0)
);
GO

CREATE TABLE Clientes(
IDCliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
Cuit CHAR(11) NOT NULL UNIQUE,
NombreCliente VARCHAR(50) NOT NULL,
NombreResponsable VARCHAR(30) NOT NULL,
ApellidoResponsable VARCHAR(30) NOT NULL,
Telefono VARCHAR(15) NOT NULL UNIQUE,
Mail VARCHAR(50) NULL UNIQUE
);
GO

CREATE TABLE DireccionCliente(
IDDireccionCliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
Calle VARCHAR(50) NOT NULL,
Altura VARCHAR(5) NULL,
Localidad VARCHAR(50) NOT NULL,
CP VARCHAR(5) NOT NULL,
Observaciones VARCHAR(255) NULL
);
GO

CREATE TABLE Entregas(
IDEntrega INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDCliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(IDCliente),
IDDireccion INT NOT NULL FOREIGN KEY REFERENCES Direccion(IDDireccion),
Fecha DATETIME NOT NULL CHECK(Fecha <= getdate()),
Importe DECIMAL (12,2) NOT NULL DEFAULT (0)
);
GO

CREATE TABLE DetalleEntrega(
IDDetalleEntrega INT NOT NULL PRIMARY KEY IDENTITY(1,1),
IDEntrega INT NOT NULL FOREIGN KEY REFERENCES Entregas(IDEntrega),
IDLote INT NOT NULL FOREIGN KEY REFERENCES Lotes(IDLote),
Cantidad INT NOT NULL DEFAULT (0),
ImporteFinal DECIMAL(12,2) NOT NULL DEFAULT (0)
);
GO